# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4963ebae2e9826a2bf2828a4ea5e5263b2a21d27cfc3337361cc2b2f555c94d8e9e03dfced1bd6b94f3bdac14950c81c9368cd5168a17547bab28d866d7ff410

test:
  secret_key_base: 5a19db7d7aab641709345594604914b7f57bb8022534eb0d1739d3fd44550c852dba7fec5df363150c3de97a70b9af293466d45bb233f3f8ac9fcc3023dd8b97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
